// Optional real-browser checks. Set PLAYWRIGHT_PATH to an installed playwright-core index.mjs.
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import fs from 'node:fs/promises';
const modulePath=process.env.PLAYWRIGHT_PATH;
if(!modulePath)throw new Error('Set PLAYWRIGHT_PATH to your playwright-core/index.mjs');
const {chromium}=await import(pathToFileURL(modulePath).href);
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await fs.mkdir(new URL('../artifacts/',import.meta.url),{recursive:true});
await page.goto('http://127.0.0.1:4177/?seed=12345');
await page.getByRole('button',{name:'FIELD MANUAL',exact:true}).click();
await page.waitForFunction(()=>DeadSignal.menu==='manual');await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.menu===null);
await page.screenshot({path:new URL('../artifacts/title.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
await page.getByRole('button',{name:'ENTER THE CITY'}).click();
await page.waitForFunction(()=>window.DeadSignal.state.time>.2);
assert.equal(await page.evaluate(()=>DeadSignal.state.players.length),1);
await page.waitForFunction(()=>DSAudio.status.state==='running');
await page.evaluate(()=>{const p=DeadSignal.state.players[0];p.hp=10;p.medkits=3;p.invuln=100;});
await page.keyboard.down('h');await page.waitForTimeout(250);
assert.deepEqual(await page.evaluate(()=>{const p=DeadSignal.state.players[0];return [p.hp,p.medkits];}),[60,2],'holding H consumes one kit');
await page.keyboard.up('h');await page.keyboard.press('h');
await page.waitForFunction(()=>DeadSignal.state.players[0].hp===100);
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].medkits),1);
await page.keyboard.press('h');await page.waitForTimeout(50);
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].medkits),1,'full health preserves inventory');
await page.evaluate(()=>{DeadSignal.state.supplies.provisions=2;});await page.keyboard.press('r');
await page.waitForFunction(()=>DeadSignal.state.supplies.provisions===1);assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].medkits),1,'R eats a ration and never touches medkits');
await page.keyboard.press('m');assert.equal(await page.evaluate(()=>DSAudio.muted),false,'M no longer toggles audio');
await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.menu==='pause');while(await page.evaluate(()=>DeadSignal.ui.items[DeadSignal.ui.focus]!=='options')){const f0=await page.evaluate(()=>DeadSignal.ui.focus);await page.keyboard.press('ArrowDown');await page.waitForFunction(f=>DeadSignal.ui.focus!==f,f0);}await page.keyboard.press('Enter');
await page.waitForFunction(()=>DeadSignal.menu==='options');
await page.keyboard.press('ArrowDown');await page.waitForFunction(()=>DeadSignal.ui.focus===1);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.waitForFunction(()=>DSAudio.muted);
await page.keyboard.press('Enter');await page.waitForFunction(()=>!DSAudio.muted);
await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.menu==='pause');await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.menu===null);
assert.ok(await page.evaluate(()=>DSAudio.status.voices<=48),'audio voices stay bounded');

assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].auto),false,'autofire starts off for stealth');
await page.keyboard.press('f');
await page.waitForFunction(()=>DeadSignal.state.players[0].auto);
await page.keyboard.press('f');
await page.waitForFunction(()=>!DeadSignal.state.players[0].auto);
await page.keyboard.down('Shift');await page.keyboard.down('w');await page.waitForTimeout(250);await page.keyboard.up('w');await page.keyboard.up('Shift');
assert.ok(await page.evaluate(()=>DeadSignal.state.players[0].stamina<100),'Shift runs and consumes stamina');
assert.ok(await page.evaluate(()=>DeadSignal.state.players[0].y<2790),'keyboard moves player');
await page.evaluate(()=>{const s=DeadSignal.state,p=s.players[0],it=s.loot.find(l=>l.type==='weapon'&&l.weapon==='ar');p.x=it.x;p.y=it.y;});
await page.waitForTimeout(100);await page.keyboard.press('e');
await page.waitForFunction(()=>DeadSignal.state.players[0].weapon==='ar');
await page.keyboard.press('q');await page.waitForFunction(()=>DeadSignal.state.players[0].backup);
await page.keyboard.press('q');await page.waitForFunction(()=>!DeadSignal.state.players[0].backup);
const firstMagazine=await page.evaluate(()=>DeadSignal.state.players[0].mag);
await page.evaluate(()=>{const s=DeadSignal.state,p=s.players[0],it=s.loot.find(l=>l.type==='weapon'&&l.weapon==='shotgun'&&!l.taken);p.x=it.x;p.y=it.y;});
await page.waitForTimeout(100);await page.keyboard.press('e');
await page.waitForFunction(()=>DeadSignal.state.players[0].weapon==='shotgun');
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].weaponInventory.length),2,'second pickup fills the other slot');
const secondMagazine=await page.evaluate(()=>DeadSignal.state.players[0].mag);
await page.keyboard.down('q');await page.waitForTimeout(250);
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].backup),true,'held Q cycles once to the pistol');
await page.keyboard.up('q');await page.keyboard.press('q');
await page.waitForFunction(()=>!DeadSignal.state.players[0].backup&&DeadSignal.state.players[0].weapon==='ar');
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].mag),firstMagazine,'first magazine survives cycling');
await page.keyboard.press('q');await page.waitForFunction(()=>DeadSignal.state.players[0].weapon==='shotgun');
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].mag),secondMagazine,'second magazine survives cycling');
await page.screenshot({path:new URL('../artifacts/two-weapons.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
await page.keyboard.down('Shift');await page.keyboard.down('w');await page.waitForTimeout(70);
await page.keyboard.press('Tab');await page.waitForFunction(()=>DeadSignal.menu==='fullmap');
await page.keyboard.up('w');await page.keyboard.up('Shift');await page.waitForTimeout(70);
const mapPosition=await page.evaluate(()=>DeadSignal.state.players[0].y);await page.waitForTimeout(100);
assert.equal(await page.evaluate(()=>DeadSignal.state.players[0].y),mapPosition,'map clears held movement');
await page.keyboard.press('Tab');await page.waitForFunction(()=>DeadSignal.menu===null);
await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.state.paused&&DeadSignal.menu==='pause');
const pausedAt=await page.evaluate(()=>DeadSignal.state.time);await page.waitForTimeout(200);
assert.equal(await page.evaluate(()=>DeadSignal.state.time),pausedAt,'pause freezes simulation');
await page.keyboard.press('Tab');await page.waitForFunction(()=>DeadSignal.menu==='fullmap');
assert.equal(await page.evaluate(()=>DeadSignal.state.time),pausedAt,'map opened from pause stays paused');
await page.keyboard.press('Tab');await page.waitForFunction(()=>DeadSignal.menu==='pause');
const n=await page.evaluate(()=>DeadSignal.ui.items.length);for(let i=0;i<n;i++)await page.evaluate(()=>DeadSignal.ui.press('down'));assert.equal(await page.evaluate(()=>DeadSignal.ui.focus),0,'menu focus wraps');
const rect=await page.evaluate(()=>DeadSignal.ui.rects().find(r=>r.id==='resume'));await page.mouse.click(rect.x+rect.w/2,rect.y+rect.h/2);await page.waitForFunction(()=>!DeadSignal.state.paused&&DeadSignal.menu===null);
await page.waitForFunction(()=>DeadSignal.ui.rects().some(r=>r.id==='map-button'));
const mapButton=await page.evaluate(()=>DeadSignal.ui.rects().find(r=>r.id==='map-button'));await page.mouse.click(mapButton.x+mapButton.w/2,mapButton.y+mapButton.h/2);await page.waitForFunction(()=>DeadSignal.menu==='fullmap');await page.keyboard.press('Tab');
await page.evaluate(()=>{const s=DeadSignal.state;for(let i=1;i<4;i++)DSGame.addPlayer(s,'test:'+i);for(const p of s.players){p.auto=true;p.weapon=['ar','shotgun','flame','smg'][p.id];p.backup=false;p.mag=DSGame.WEAPONS[p.weapon].mag;p.x=(p.id-1.5)*35;p.y=2620+(p.id%2)*35;p.invuln=100;}s.camera.x=0;s.camera.y=2620;for(let i=0;i<22;i++)DSGame.spawn(s,i%4===0?'runner':'walker',Math.cos(i)*230,2620+Math.sin(i)*150);});
await page.waitForTimeout(700);await page.screenshot({path:new URL('../artifacts/street.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
await page.evaluate(()=>{const s=DeadSignal.state;DSBoss.start(s,DSGame.api(s));s.boss.hp=s.boss.maxHp*.3;for(const p of s.players)p.invuln=100;});
await page.waitForTimeout(1800);await page.screenshot({path:new URL('../artifacts/boss.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
await page.setViewportSize({width:1024,height:600});await page.waitForTimeout(150);
await page.screenshot({path:new URL('../artifacts/compact.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
await page.evaluate(()=>{for(const p of DeadSignal.state.players)p.upgrades=1;});
await page.waitForTimeout(100);
await page.screenshot({path:new URL('../artifacts/medkits-upgrades.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
const badges=await page.evaluate(()=>DeadSignal.ui.rects().filter(r=>r.id.startsWith('up:')));assert.equal(badges.length,4,'four survivors each show one upgrade badge, not live choices');
// 1024x600 is below the 720 px budget viewports: text keeps its 12 px floor, so only the dock height is checked here (tools/hud-matrix.mjs covers the budget viewports)
const report=await page.evaluate(()=>DSHud.report());assert.ok(report.budget.coreTextPx>=12&&report.bottom===80&&report.budget.areaPct<=22,'pending upgrades do not grow the dock: '+JSON.stringify(report.budget));
await page.mouse.click(badges[2].x+badges[2].w/2,badges[2].y+badges[2].h/2);await page.waitForFunction(()=>DeadSignal.menu==='upgrade'&&DSHud.upgradeFor===2&&DeadSignal.state.paused);
await page.waitForFunction(()=>DeadSignal.ui.rects().some(r=>r.id==='offer:1'));const card=await page.evaluate(()=>DeadSignal.ui.rects().find(r=>r.id==='offer:1'));await page.mouse.click(card.x+card.w/2,card.y+card.h/2);
await page.waitForFunction(()=>DeadSignal.state.players[2].upgrades===0&&DeadSignal.menu==='pause');await page.keyboard.press('Escape');await page.waitForFunction(()=>DeadSignal.menu===null);
await page.evaluate(()=>DeadSignal.ui.open('manual'));await page.waitForTimeout(100);
await page.screenshot({path:new URL('../artifacts/manual.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')});
assert.deepEqual(errors,[],'no browser runtime errors');
console.log('browser passed: medkits, audio startup/mute, title/manual, movement, auto toggle, weapon pickup/switch, map, pause, four-player combat and boss render');
await browser.close();
